# cYK algorithm for checking if a string is in the language generated by a CFG

def CYK(CFG, string):
	table = [None for _ in range(len(string))]*len(string)
	start = 0
	end = 1
	for i in range(len(string)):
		table[0][i] = inCFG(string[i], CFG)

	for i in range(1, len(string)):
		for j in range(len(string)-i):
			table[i][j] = set()



def inCFG(s, CFG):
	return {k for k, v in CFG.items() if s in v}


cfg = {
	"S":{"AB", "BC"},
    "A":{"BA", "a"},
	"B": {"CC", "b"},
	"C": {"AB", "a"}
       }